# -*- coding: utf-8 -*-
"""Training YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1MaoEaA63PNKOOEkqrVq0sc5oh6MwPv
"""

pip install ultralytics

!pip install clearml

# Commented out IPython magic to ensure Python compatibility.
# %env CLEARML_WEB_HOST=https://app.clear.ml
# %env CLEARML_API_HOST=https://api.clear.ml
# %env CLEARML_FILES_HOST=https://files.clear.ml
# %env CLEARML_API_ACCESS_KEY=42H1WL0H1K07NJ0U99WF
# %env CLEARML_API_SECRET_KEY=vyrNvnbKO8kfNGOJhUwy0MOGykKJBljuE5omTIXws5irKetkZu

from clearml import Task
task = Task.init(project_name="BTP", task_name="FineTuneYOLO")

import zipfile
import requests
import cv2
import matplotlib.pyplot as plt
import glob
import random
import os

# os.makedirs('datasets', exist_ok=True)

# %cd datasets
# %pwd

# import os

# # Get the path to the datasets folder
# datasets_folder = os.path.join('..', 'datasets')

# # Get the path to the jip.zip file
# jip_zip_path = os.path.join(datasets_folder, 'jip.zip')

# # Check the type of file
# file_type = os.path.splitext(jip_zip_path)[1]

# # Print the type of file
# print(f"The type of file is: {file_type}")



# # Unzip the data file
# def unzip(zip_file=None):

#         with zipfile.ZipFile(zip_file) as z:
#             z.extractall("./")
#             print("Extracted all")


# unzip('jip.zip')



EPOCHS = 5
!yolo task=detect mode=train model=yolov8n.pt imgsz=1280 data=/content/drive/MyDrive/BTP24/Data/data.yaml epochs={EPOCHS} batch=8 name=yolov8n_v8_50e

!yolo task=detect mode=train model=yolov8m.pt imgsz=1280 data=/content/drive/MyDrive/BTP24/Data_oxford/data_oxford.yaml epochs=50 batch=8 name=yolov8m_v8_50e

import shutil
src_path = '/content/runs'
dest_path = '/content/drive/MyDrive/BTP24/oxford1'
shutil.copytree(src_path, dest_path)

from google.colab import drive
drive.mount('/content/drive')

!yolo task=detect mode=val model=/content/drive/MyDrive/BTP24/runs0/detect/yolov8m_v8_50e/weights/best.pt name=yolov8m_eval data=/content/drive/MyDrive/BTP24/Data/data.yaml imgsz=1280

import shutil
src_path = '/content/runs'
dest_path = '/content/drive/MyDrive/BTP24/runs0_eval'
shutil.copytree(src_path, dest_path)

import cv2

!yolo task=detect mode=predict model=/content/drive/MyDrive/BTP24/runs0/detect/yolov8m_v8_50e/weights/best.pt source=/content/drive/MyDrive/BTP24/video_data/try3.png show=True imgsz=1280 name=yolov8n_v8_50e_infer1280 hide_labels=True

from moviepy.editor import *

path="/content/runs/detect/yolov8n_v8_50e_infer12807/try5.avi"

clip=VideoFileClip(path)
clip.ipython_display(width=280)



